<a href="https://colab.research.google.com/github/dpmanoj/ALVA_SESSION/blob/master/Day_3_Session_2_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#program1
#NumPy program to create a random integer nos of size 20 and sort it.
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)



[16 12 15  0  7 11  4 19 13 17  8 10  9 18  6  3  5  2 14  1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
#program2
#NumPy program to generate 8 random integers between 100 and 300
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)


[139 185 272 221 185 176 185 197]


In [13]:
#program3
#NumPy program to create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.68632866 0.11454998 0.99775528 0.16563216 0.07622172 0.23882121
  0.84243301 0.93357795 0.26029708 0.17043885]
 [0.03169277 0.11183956 0.86927071 0.58137288 0.44492467 0.42699126
  0.57222495 0.97542552 0.0217182  0.59516129]
 [0.43375629 0.39135589 0.9842827  0.90819851 0.14378024 0.43099985
  0.34270166 0.90918755 0.22910377 0.33618331]
 [0.23234309 0.03682051 0.54650639 0.51755725 0.46938464 0.77019611
  0.7467615  0.67180992 0.12055527 0.55048974]
 [0.68296105 0.09919142 0.57720343 0.10667497 0.26182255 0.62681633
  0.92247704 0.49672254 0.53217092 0.72717295]
 [0.11521109 0.64875413 0.71364828 0.86150649 0.27042778 0.28307119
  0.43483591 0.82526164 0.89470491 0.40038512]
 [0.26577038 0.10208031 0.8810092  0.36996683 0.07665979 0.98794157
  0.1457708  0.95089593 0.04208118 0.1084405 ]
 [0.81753297 0.49105929 0.92240573 0.0913432  0.91539426 0.05725168
  0.26881324 0.3253895  0.93342663 0.3131249 ]
 [0.44510803 0.30207902 0.9422209  0.40707932 0.94127681 0.92119

In [26]:
#program4
#NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the  array and store them into a variable
import numpy as np
x = np.random.rand(4, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("2nd and 3rd  rows of the above array:")
print(y[1],y[2])




Original array: 
[[0.82404133 0.81176259 0.11102572 0.56952306]
 [0.39954005 0.9620891  0.02703371 0.80845696]
 [0.73242023 0.74308361 0.17892059 0.9519656 ]
 [0.79768423 0.71178782 0.1675435  0.58085707]]
2nd and 3rd  rows of the above array:
[0.39954005 0.9620891  0.02703371 0.80845696] [0.73242023 0.74308361 0.17892059 0.9519656 ]


In [ ]:
#Program5
#Pandas program to get the details of the movies record number divisable by 5 of the DataFrame 
import pandas as pd
from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['movie_metadata.csv']))
movie = df.iloc[df/5]
print("Movie Record Number:")
print(movie)


In [ ]:
#Program6
#Write a Pandas program to sort the DataFrame based on country  and language from dataset of  movie_metadata.csv
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['movie_metadata.csv.txt']))
print("sorted by country and language")
small_df = df[['language','country']]
result = small_df.sort_values('language','country',)
print("DataFrame based on Country and language")
print(result)


In [45]:
#Program7
#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields
import pandas as pd
from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['movie_metadata.csv.txt']))
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)


Saving movie_metadata.csv.txt to movie_metadata.csv (11).txt
First 10 rows of the DataFrame:
  color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,
0  Color,James Cameron,723,178,0,855,Joel David M...                                                                                                                                                                                                                                                                                                                                                                                
1  Color,Gore Verbinski,302,169,563,1000,Orlando ...             

In [46]:
#Program8
#Write a Pandas program to get the elements of an array values into column-wise
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [48]:
#Program9
#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000
import pandas as pd
s = pd.Series(data = [1,2,3,5,7,11,13,17,19,23])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())
print("Min of the said Data Series:")
print(s.min())
print("Max of the said Data Series:")
print(s.max())


Original Data Series:
0     1
1     2
2     3
3     5
4     7
5    11
6    13
7    17
8    19
9    23
dtype: int64
Mean of the said Data Series:
10.1
Standard deviation of the said Data Series:
7.723700897597961
Min of the said Data Series:
1
Max of the said Data Series:
23


In [55]:
#Program10
#Write a Pandas program to sort a given Series
import pandas as pd
s = pd.Series(['100','200','300' ,'400', '500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)




Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


In [56]:
#Program11
#Write a Pandas program to convert a given Series to an array
import numpy as np
s1 = pd.Series(['100','200','300' ,'400', '500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


In [57]:
#Program12
#Write a Pandas program to convert a NumPy array to a Pandas series.
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50, 1000])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[  10   20   30   40   50 1000]
Converted Pandas series:
0      10
1      20
2      30
3      40
4      50
5    1000
dtype: int64


In [58]:
#Program14
#Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 100])
ds2 = pd.Series([1, 3, 5, 7, 9, 99])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0      3.0
1      7.0
2     11.0
3     15.0
4    109.0
5      NaN
dtype: float64
Subtract two Series:
0     1.0
1     1.0
2     1.0
3     1.0
4    91.0
5     NaN
dtype: float64
Multiply two Series:
0      2.0
1     12.0
2     30.0
3     56.0
4    900.0
5      NaN
dtype: float64
Divide Series1 by Series2:
0     2.000000
1     1.333333
2     1.200000
3     1.142857
4    11.111111
5          NaN
dtype: float64
